Program registroCarro; 
type
	Opcao = record
	  opcional: array [1..4] of String;
	  Valor: array [1..4] of real;
	end;
	FichaCarros = record 
		model: string; 
		mar: string; 
		compraValor: real; 
		vendaValor: real;
		adicional: Opcao;
end; 

var 
	i, j: integer; 
	carro: array[1..7] of FichaCarros;
	TotCompra, TotVenda, TotCarro, Lucro: real; 
Begin 
	for i:= 1 to 7 do 
	begin 
		write('Digite a marca do carro...: ' ); 
		readln(carro[i].mar); 
		write('Digite o modelo do carro...: ' ); 
		readln(carro[i].model); 
		write('Digite o valor de compra do carro...: ' ); 
		readln(carro[i].compraValor); 
		write('Digite o valor de venda do carro...: ' ); 
		readln(carro[i].vendaValor); 
		writeln; 
		writeln;
		for j:= 1 to 4 do
		begin
			writeln('Opcional ...: ', j);
			readln(carro[i].adicional.opcional[j]);
			writeln('Valor ...: ', j);
			readln(carro[i].adicional.Valor[j]);
		end; 
	end; 
	writeln; 
	writeln('========== REGISTROS =========='); 
	writeln; 
	writeln; 
	writeln('========== CARRO 1 =========='); 
	writeln('Marca...: ' , carro[1].mar); 
	writeln('Modelo...: ' , carro[1].model); 
	writeln('Valor de Compra...:' , carro[1].compraValor:7:2, 'R$'); 
	writeln('Valor de Venda...: ' , carro[1].vendaValor:7:2, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS ==========');
	writeln('Adicional 1...: ', carro[1].adicional.opcional[1]);
	writeln('Valor...: ', carro[1].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[1].adicional.opcional[2]);
	writeln('Valor...: ', carro[1].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[1].adicional.opcional[3]);
	writeln('Valor...: ', carro[1].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[1].adicional.opcional[4]);
	writeln('Valor...: ', carro[1].adicional.Valor[4]:4:2);  
	writeln; 
	writeln;
	TotCarro := carro[1].vendaValor + carro[1].adicional.Valor[1] + carro[1].adicional.Valor[2] + carro[1].adicional.Valor[3] + carro[1].adicional.Valor[4];
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln; 
	writeln('========== CARRO 2 =========='); 
	writeln('Marca...: ' , carro[2].mar); 
	writeln('Modelo...: ' , carro[2].model); 
	writeln('Valor de Compra...:' , carro[2].compraValor:7:2, 'R$'); 
	writeln('Valor de Venda...: ' , carro[2].vendaValor:7:2, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS ==========');
	writeln('Adicional 1...: ', carro[2].adicional.opcional[1]);
	writeln('Valor...: ', carro[2].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[2].adicional.opcional[2]);
	writeln('Valor...: ', carro[2].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[2].adicional.opcional[3]);
	writeln('Valor...: ', carro[2].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[2].adicional.opcional[4]);
	writeln('Valor...: ', carro[2].adicional.Valor[4]:4:2);
	writeln;
	writeln;
	TotCarro := carro[2].vendaValor + carro[2].adicional.Valor[1] + carro[2].adicional.Valor[2] + carro[2].adicional.Valor[3] + carro[2].adicional.Valor[4];
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln; 
	writeln('========== CARRO 3 =========='); 
	writeln('Marca...: ' , carro[3].mar); 
	writeln('Modelo...: ' , carro[3].model); 
	writeln('Valor de Compra...:' , carro[3].compraValor, 'R$'); 
	writeln('Valor de Venda...: ' , carro[3].vendaValor, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS =========='); 
	writeln('Adicional 1...: ', carro[3].adicional.opcional[1]);
	writeln('Valor...: ', carro[3].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[3].adicional.opcional[2]);
	writeln('Valor...: ', carro[3].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[3].adicional.opcional[3]);
	writeln('Valor...: ', carro[3].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[3].adicional.opcional[4]);
	writeln('Valor...: ', carro[3].adicional.Valor[4]:4:2);
	writeln; 
	writeln;
	TotCarro := carro[3].vendaValor + carro[3].adicional.Valor[1] + carro[3].adicional.Valor[2] + carro[3].adicional.Valor[3] + carro[3].adicional.Valor[4] ;
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln; 
  writeln('========== CARRO 4 =========='); 
	writeln('Marca...: ' , carro[4].mar); 
	writeln('Modelo...: ' , carro[4].model); 
	writeln('Valor de Compra...:' , carro[4].compraValor:7:2, 'R$'); 
	writeln('Valor de Venda...: ' , carro[4].vendaValor:7:2, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS ==========');
	writeln('Adicional 1...: ', carro[4].adicional.opcional[1]);
	writeln('Valor...: ', carro[4].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[4].adicional.opcional[2]);
	writeln('Valor...: ', carro[4].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[4].adicional.opcional[3]);
	writeln('Valor...: ', carro[4].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[4].adicional.opcional[4]);
	writeln('Valor...: ', carro[4].adicional.Valor[4]:4:2); 
	writeln; 
	writeln;
	TotCarro := carro[4].vendaValor + carro[4].adicional.Valor[1] + carro[4].adicional.Valor[2] + carro[4].adicional.Valor[3] + carro[4].adicional.Valor[4];
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln; 
	writeln('========== CARRO 5 =========='); 
	writeln('Marca...: ' , carro[5].mar); 
	writeln('Modelo...: ' , carro[5].model); 
	writeln('Valor de Compra...:' , carro[5].compraValor:7:2, 'R$'); 
	writeln('Valor de Venda...: ' , carro[5].vendaValor:7:2, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS ==========');
	writeln('Adicional 1...: ', carro[5].adicional.opcional[1]);
	writeln('Valor...: ', carro[5].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[5].adicional.opcional[2]);
	writeln('Valor...: ', carro[5].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[5].adicional.opcional[3]);
	writeln('Valor...: ', carro[5].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[5].adicional.opcional[4]);
	writeln('Valor...: ', carro[5].adicional.Valor[4]:4:2);
	writeln; 
	writeln;
	TotCarro := carro[5].vendaValor + carro[5].adicional.Valor[1] + carro[5].adicional.Valor[2] + carro[5].adicional.Valor[3] + carro[5].adicional.Valor[4];
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln;
	writeln('========== CARRO 6 =========='); 
	writeln('Marca...: ' , carro[6].mar); 
	writeln('Modelo...: ' , carro[6].model); 
	writeln('Valor de Compra...:' , carro[6].compraValor:7:2, 'R$'); 
	writeln('Valor de Venda...: ' , carro[6].vendaValor:7:2, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS ==========');
	writeln('Adicional 1...: ', carro[6].adicional.opcional[1]);
	writeln('Valor...: ', carro[6].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[6].adicional.opcional[2]);
	writeln('Valor...: ', carro[6].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[6].adicional.opcional[3]);
	writeln('Valor...: ', carro[6].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[6].adicional.opcional[4]);
	writeln('Valor...: ', carro[6].adicional.Valor[4]:4:2);
	writeln; 
	writeln;
	TotCarro := carro[6].vendaValor + carro[6].adicional.Valor[1] + carro[6].adicional.Valor[2] + carro[6].adicional.Valor[3] + carro[6].adicional.Valor[4];
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln;
	writeln('========== CARRO 7 =========='); 
	writeln('Marca...: ' , carro[7].mar); 
	writeln('Modelo...: ' , carro[7].model); 
	writeln('Valor de Compra...:' , carro[7].compraValor:7:2, 'R$'); 
	writeln('Valor de Venda...: ' , carro[7].vendaValor:7:2, 'R$');
	writeln;
	writeln;
	writeln('========== ADICIONAIS ==========');
	writeln('Adicional 1...: ', carro[7].adicional.opcional[1]);
	writeln('Valor...: ', carro[7].adicional.Valor[1]:4:2);
	writeln('Adicional 2...: ', carro[7].adicional.opcional[2]);
	writeln('Valor...: ', carro[7].adicional.Valor[2]:4:2); 
	writeln('Adicional 3...: ', carro[7].adicional.opcional[3]);
	writeln('Valor...: ', carro[7].adicional.Valor[3]:4:2); 
	writeln('Adicional 4...: ', carro[7].adicional.opcional[4]);
	writeln('Valor...: ', carro[7].adicional.Valor[4]:4:2);
	writeln;
	writeln;
	TotCarro := ( carro[7].vendaValor + carro[7].adicional.Valor[1] + carro[7].adicional.Valor[2] + carro[7].adicional.Valor[3] + carro[7].adicional.Valor[4]);
	writeln('VALOR TOTAL DO CARRO');
	writeln(TotCarro:7:2, 'R$');
	writeln; 
	writeln;
	TotCompra := carro[1].compraValor + carro[2].compraValor + carro[3].compraValor + carro[4].compraValor + carro[5].compraValor + carro[6].compraValor + carro[7].compraValor;
	TotVenda := carro[1].vendaValor + carro[2].vendaValor + carro[3].vendaValor + carro[4].vendaValor + carro[5].vendaValor + carro[6].vendaValor + carro[7].vendaValor;
	Lucro:= (TotVenda - TotCompra);
	writeln (' O total de vendas da loja foi de...: ', TotVenda:7:2, 'R$'); 
	writeln (' O total de compras da loja foi de...: ', TotCompra:7:2, 'R$');
	writeln (' O lucro da loja foi de...: ', Lucro:7:2, 'R$'); 
	writeln; 
			 End.